### ISSUE TITLE
Foundry VTT 11 compatibility

### ISSUE THREAD

**Issue by DrMcCoy** [p4535992/foundryvtt-safety-tools#5]
A few weeks ago, I set up a new Foundry VTT instance, this time V11 (and a different game system), for a friend who wants to take over the DM seat for a while. I installed my usual set of modules and noticed that Safety Tools doesn't work. In fact, the whole tools sidebar fails to draw with Safety Tools enabled.

Have you already looked into making this V11 compatible? Do you have something in the works?

I'll probably start testing moving the instances of other groups to V11 some time next week or so. I might also have a look if I can figure out what's the deal with Safety Tools, but I can't promise anything, especially since JavaScript/TypeScript/webdev stuff isn't really my scene.

**Comment by DrMcCoy** [comment]
Hmm, or maybe that was an incompatibility with the DSA5 system?

Because testing this just now with a Pathfinder 1e instance, Safety Tools works fine if you modify module.json to claim compat...

**Comment by lektu** [comment]
Apparently, modifying module.json to remove the maximum parameter allows it to work on V11.
That's a bit of a pain when using The Forge, though, because it means modifying the module outside it and loading it as a custom module, which is always a bit more fragile. It'd be great to get a V11 release, specially if it seems to be working ok already.

**Comment by Tyrim** [comment]
There's something else going on, likely a different mod, because this still works great on my v11 install.

**Comment by lektu** [comment]
> There's something else going on, likely a different mod, because this still works great on my v11 install.

To make it work on V11 I had to modify module.json. Did you?

**Comment by Tyrim** [comment]
> 

I did not have to modify anything.

**Comment by lektu** [comment]
That's weird. My Foundry V11 doesn't even let me install 0.5.3, it says it is "for a previous version" of Foundry.

**Comment by p4535992** [comment]
done a  upgrdae for v11

**Comment by DrMcCoy** [comment]
Thanks!
